### ISSUE TITLE
Exporting freezes the process

### ISSUE THREAD

**Issue by javiersalcedopuyo** [zakorgy/voxel-editor#38]
**Description**:   
The process freezes when trying to export to file.
Seems to be an issue with *nfd::open_save_dialog* in *Controls::update*, since it never reaches the match after it.

**Seen in platform**: macOS Catalina
**Seen in commit**: 34b947a50ae1ddeaa568f519061a1eaa08fa06f3
**Steps to reproduce**:
1. Create any design
2. Click on "Export to .obj"
3. Interact with the dialog prompt

**Comment by zakorgy** [comment]
Fixed in #39
